[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
uuid = { version = "1.11", features = ["v4"] }
dirs = "5.0"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
